# Generated by Django 4.2.2 on 2023-08-07 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_alter_mailmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailmessage',
            options={'ordering': ['title'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['email'], 'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción'),
        ),
    ]
