# Generated by Django 4.2.2 on 2023-08-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_alter_mailmessage_options_alter_subscribers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailmessage',
            options={'ordering': ['id'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['id'], 'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
    ]
