# Generated by Django 4.2.2 on 2023-08-09 00:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0006_alter_mailmessage_options_alter_subscribers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='message',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Mensaje'),
        ),
    ]
