# Generated by Django 4.2.2 on 2023-08-17 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_alter_mailmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
