# Generated by Django 4.2.2 on 2023-08-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_subscribers_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
